// Copyright 2023 jack (@waffle87)
// SPDX-License-Identifier: GPL-2.0-or-later
#pragma once

#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET

#define I2C_DRIVER I2CD1
#define I2C1_SDA_PIN GP22
#define I2C1_SCL_PIN GP23

#define AUDIO_PIN GP28
#define AUDIO_PWM_DRIVER PWMD6
#define AUDIO_INIT_DELAY
#define AUDIO_PWM_CHANNEL RP2040_PWM_CHANNEL_A
#define STARTUP_SONG SONG(ODE_TO_JOY)

//UEFI was not detecting some of my boards
#define SPLIT_WATCHDOG_ENABLE
#define SPLIT_MAX_CONNECTION_ERRORS 30
#define SPLIT_CONNECTION_CHECK_TIMEOUT 500
#define SPLIT_USB_DETECT
#define SPLIT_USB_TIMEOUT 1000
#define SPLIT_USB_TIMEOUT_POLL 20
#define SPLIT_WATCHDOG_TIMEOUT 5000

// Double tap left shift to turn on CAPS WORD
#define DOUBLE_TAP_SHIFT_TURNS_ON_CAPS_WORD

// #define SPLIT_POINTING_ENABLE
// #define POINTING_DEVICE_LEFT
// #define ANALOG_JOYSTICK_Y_AXIS_PIN GP26
// #define ANALOG_JOYSTICK_X_AXIS_PIN GP27
// #define POINTING_DEVICE_INVERT_Y
// #define POINTING_DEVICE_INVERT_X

